[project]
name = "dotfiles"
version = "9.0.13"
description = "Personal development laboratory"
authors = [{ name = "Itzalak", email = "itzalak@tuta.io" }]
readme = "README.md"
keywords = ["dotfiles", "archlinux", "macos"]
requires-python = ">=3.13"
dependencies = [
  "pytest >= 8.3.3",
  "pyyaml >= 6.0.2",
  "python-dotenv >= 1.0.1",
  "toml >= 0.10.2",
  "click>=8.3.1",
]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.commitizen]
name = "cz_customize"
tag_format = "v$major.$minor.$patch"
version_scheme = "semver"
update_changelog_on_bump = true
version_provider = "uv"

[tool.uv]
required-version = ">=0.7.3"

[tool.commitizen.customize]
schema = "<type>[(scope)]: <message>"
schema_pattern = "^(break|feat|fix|docs|chore)(\\([^()\\r\\n]+\\))?(!)?:\\s.*"
bump_pattern = "^(break|feat|fix|chore)"
bump_map = { "break" = "MAJOR", "feat" = "MINOR", "fix" = "PATCH", "chore" = "PATCH" }
commit_parser = "^(?P<change_type>feat|fix|break|docs|chore)(?:\\((?P<scope>[^()\\r\\n]*)\\))?(?P<breaking>!)?:\\s(?P<message>.*)?"
changelog_pattern = "^(break|feat|fix|chore|docs)"
change_type_order = [
  "⚠️ Breaking Change",
  "🚀 New Feature",
  "🧹 Chore",
  "🐛 Fix",
  "📚 Documentation",
]

[tool.commitizen.customize.change_type_map]
break = "⚠️ Breaking Change"
feat = "🚀 New Feature"
chore = "🧹 Chore"
fix = "🐛 Fix"
docs = "📚 Documentation"
