version: '3'

includes:
  brew: "./taskfiles/taskfile.brew.yml"
  gotask: "./taskfiles/taskfile.gotask.yml"
  depository: "./taskfiles/taskfile.depository.yml"
  linux: "./taskfiles/taskfile.linux.yml"
  macos: "./taskfiles/taskfile.macos.yml"
  neovim: "./taskfiles/taskfile.neovim.yml"
  python: "./taskfiles/taskfile.python.yml"
  sdkman: "./taskfiles/taskfile.sdkman.yml"
  terminal: "./taskfiles/taskfile.terminal.yml"
  niri: "./taskfiles/taskfile.niri.yml"

tasks:

  default:
    desc: Default
    cmds:
      - |
        echo "Home dir: {{.HOME}}"
        echo "Root dir: {{.ROOT_DIR}}"
        echo "Working dir: {{.USER_WORKING_DIR}}"
        echo "OS: {{OS}}"
        task --list
    silent: true

  assert:
    cmds:
      - for:
          var: REQUIRED_TOOLS
          split: ','
          as: TOOL
        cmd: |
          [ -n "$(which {{ .TOOL }})" ] || ( \
            echo "ERROR: `{{ .TOOL }}` not found" && exit 1; \
          )
    silent: true
    internal: true
    vars:
      REQUIRED_TOOLS: uv, prek

  setup:
    deps: [assert]
    desc: Set up uv and prek
    cmds:
      - task: prek_setup
      - uv sync

  update:
    deps: [assert]
    desc: Update uv and prek
    cmds:
      - task: uv_update
      - prek auto-update
      - prek cache gc
      - prek validate-config

  prek_setup:
    internal: true
    deps: [assert]
    desc: Initialize prek
    cmds:
      - prek install
      - prek auto-update
      - prek validate-config

  uv_update:
    internal: true
    deps: [assert]
    desc: Update uv dependencies
    cmds:
      - rm -rf .venv
      - uv lock --upgrade
      - uv sync

  run:
    aliases: [prek_run]
    deps: [assert]
    desc: Run prek on all files
    cmds:
      - prek run --color always --all-files

  uv:
    deps: [assert]
    desc: Refresh uv environment
    cmds:
      - uv sync

  test:
    aliases: [uv_test]
    deps: [assert]
    desc: Run tests using uv
    cmds:
      - uv run pytest
