#! /bin/sh

## WM Config ##
bspc config border_width                2
bspc config window_gap                  10
bspc config bottom_padding              0
bspc config split_ratio                 0.5

focused=$(decorate_load_xcolors 'color4' '#a89984')
normal=$(decorate_load_xcolors 'color0' '#010201')

bspc config normal_border_color         $normal
bspc config active_border_color         $normal
bspc config focused_border_color        $focused

bspc config click_to_focus              any
bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors    true
bspc config borderless_monocle          true
bspc config gapless_monocle             true

## Special windows ##
bspc rule -a Zathura state=tiled

## auto-start ## 
picom &
dunst &
sxhkd &
# necessary for some applications like intelliJ
wmname LG3D &

refresh_monitors --all &
refresh_desktop &
#xset dpms 500 & lock_desktop start &
