# Special workspace
# TODO: Rules are not working, new update broke it all
#
# windowrule {
#   name = windowrule-1
#   workspace = special:SCRATCH silent
#   match:class = ^(Steam|steam|steamwebhelper)
# }
