# Special workspace
windowrule {
  name = windowrule-1
  workspace = special:SCRATCH silent
  match:class = ^(Steam|steam|steamwebhelper)
}

windowrule {
  name = windowrule-2
  workspace = special:CONSOLE
  match:class = kitty
}
