# Brewfile

# taps
tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/services'

# Make sure apps get installed in system Applications dir
cask_args appdir: '/Applications'

# git
brew 'git'
brew 'git-extras'
brew 'git-filter-repo'
brew 'lazygit'

# python
brew 'python'
brew 'pipenv'
brew 'pip-tools'
brew 'virtualenv'
brew 'ranger'
brew 'pre-commit'
brew 'cookiecutter'
brew 'poetry'
brew 'commitizen'
brew 'pipx'
# brew 'httpie'

# Jvm
# java, groovy, scala, kotlin, maven and gradle are managed by sdkman
brew 'ktlint'

# binaries
brew 'base64'
brew 'bat'
brew 'bottom'
brew 'coreutils'
brew 'curl'
brew 'fd'
brew 'findutils'
brew 'fzf'
brew 'gnupg'
brew 'gnutls'
brew 'grep'
brew 'jq'
brew 'nano'
brew 'nvim'
brew 'openssl'
brew 'ripgrep'
brew 'shellcheck'
brew 'starship'
brew 'stow'
brew 'telnet'
brew 'tldr'
brew 'trash'
brew 'tree'
brew 'wget'
brew 'yq'
brew 'zoxide'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'


# aws
# brew 'awscli'

# azure
# brew 'azure-cli'

# db
brew 'postgresql'

# lua
brew 'lua'
brew 'stylua'
brew 'luarocks'

# kubernetes
brew 'k9s'
brew 'helm'
brew 'kubectl'
# brew 'kustomize'
brew 'kubectx'
tap 'boz/repo'
brew 'boz/repo/kail'

# jwt
tap 'mike-engel/jwt-cli'
brew 'jwt-cli'

# terraform
brew 'terraform'
brew 'tflint'
# terraform and tfenv conflict if both are installed
# brew 'tfenv'
# brew 'tfsec'

# Kafka
brew "kcat"

# frontend
brew 'yarn'
# brew 'nvm'
brew 'npm'
brew 'node'

# docker
cask 'docker'
brew 'lazydocker'

# applications
cask 'chromium'
cask 'firefox'
cask 'firefox-developer-edition'
# cask 'insomnia'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'keepassxc'
cask 'microsoft-office'
cask 'microsoft-teams'
cask 'obsidian'
# cask 'postman'
cask 'rectangle'
cask 'slack'
cask 'spotify', args: { require_sha: false }
cask 'ticktick'
cask 'visual-studio-code'
cask 'wezterm'

# fonts
cask 'font-fira-code'
cask 'font-fira-mono-nerd-font'
cask 'font-hack-nerd-font'
cask 'font-iosevka'
cask 'font-iosevka-nerd-font'

# hardware
cask 'keymapp'

# AI
brew 'ollama'

# In test
# brew 'magic-wormhole'
# brew 'microsoft-edge'
