# Brewfile

# taps
tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/services'
tap 'homebrew/cask-drivers'
tap 'int128/kubelogin'

# Make sure apps get installed in system Applications dir
cask_args appdir: '/Applications'

# git
brew 'git'
brew 'git-extras'
brew 'git-filter-repo'
brew 'pre-commit'

# Jvm
brew 'gradle'
brew 'groovy'
brew 'kotlin'
brew 'ktlint'
brew 'maven'
cask 'zulu8'
cask 'zulu11'
cask 'zulu17'
brew 'scala'

# binaries
brew 'awscli'
brew 'base64'
brew 'bottom'
brew 'coreutils'
brew 'curl'
brew 'fd'
brew 'findutils'
brew 'fzf'
brew 'glow'
brew 'gnupg'
brew 'gnutls'
brew 'grep'
brew 'httpie'
brew 'jq'
brew 'lazygit'
brew 'nano'
brew 'nvim'
brew 'openssl'
brew 'ranger'
brew 'ripgrep'
brew 'shellcheck'
brew 'starship'
brew 'stow'
brew 'telnet'
brew 'tldr'
brew 'trash'
brew 'tree'
brew 'wget'
brew 'yq'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

# db
cask 'dbeaver-community'
brew 'postgresql@14'

# lua
brew 'lua'
brew 'stylua'
brew 'luarocks'

# python
brew 'python'
brew 'python3'
brew 'python@3.10'
brew 'pipenv'
brew 'pip-tools'
brew 'virtualenv'
brew 'cookiecutter'
brew 'poetry'

# kubernetes
brew 'helm'
brew 'kubectl'
brew 'int128/kubelogin/kubelogin'

# terraform
brew 'tfenv'
brew 'tflint'
brew 'tfsec'

# vscode
cask 'visual-studio-code'

# frontend
brew 'yarn'
brew 'npm'
brew 'node'

# docker
cask 'docker'
brew 'docker-compose'

# diagrams
brew 'plantuml'
brew 'graphviz'

# applications
cask 'alacritty'
cask 'chromium'
cask 'firefox'
cask 'firefox-developer-edition'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'microsoft-office'
cask 'microsoft-teams'
cask 'obsidian'
cask 'postman'
cask 'slack'
cask 'spectacle'
cask 'spotify', args: { require_sha: false }
cask 'wezterm'

# fonts
cask 'font-fira-code'
cask 'font-fira-mono-nerd-font'
cask 'font-hack-nerd-font'
cask 'font-iosevka'
cask 'font-iosevka-nerd-font'

# hardware
cask 'zsa-wally'
cask 'displaylink'
cask 'displaylink-login-extension'
