#!/usr/bin/env python3

# This script flattens a json file based on terminal.sexy export
# It expects thepath to the source filename and creates a new colorcheme json file, 
# if doesn't exist, in resources folder with origin file name

import json
import os
import sys

HOME = os.getenv("HOME")
XDG_CONFIG_DIR = os.getenv("XDG_CONFIG_HOME", os.path.join(HOME, ".cache"))

if len(sys.argv) != 2:
    sys.exit(f'Source filename argument were expected, instead {len(sys.argv)} arguments were found')

SRC_FILE = sys.argv[1]
if os.path.exists(SRC_FILE) is False:
    sys.exit(f'File {SRC_FILE} is not present!')

filename = os.path.basename(os.path.splitext(SRC_FILE)[0])
TARGET_FILE = f'{XDG_CONFIG_DIR}/decorator/resources/{filename}.json'
if os.path.exists(TARGET_FILE) is True:
    sys.exit(f'File {TARGET_FILE} already exists!')

lines = {} 

with open(SRC_FILE, 'rt') as file:
    d = json.load(file)
    for k, v in d.items():
        if isinstance(v, list):
            for index in range(len(v)):
                lines[f'color{index}'] = v[index]
        elif k == 'name':
            if v == '':
                lines[k] = sys.argv[1]
            else:
                lines[k] = v
        else:
            lines[k] = v

print(lines)

with open(TARGET_FILE, 'x', encoding='utf-8') as entries:
    json.dump(lines, entries, indent=2)
