#! /bin/bash

echo 'Reloading environment colour scheme'

if [[ $# -ne 1 ]]; then
  echo "Illegal number of parameters $#" >&2
  echo "Usage: command [COLORSCHEME]"
  echo "Color schemes can be found under .config/decorator/resources"
  exit 2
fi

echo "Creating new output files"
./decorate_new_output_files "$1"
sleep 2

echo "Loading xresources with the new colorscheme"
xrdb "$HOME"/.Xresources
sleep 2

echo "WARNING: Color scheme was updated to '$1'"
