# Brewfile

# taps
tap 'boz/repo'
tap 'mike-engel/jwt-cli'
tap 'hashicorp/tap'

# Install apps in macos Applications directory
cask_args appdir: '/Applications'

brew 'azure-cli'
brew 'base64'
brew 'bat'
brew 'bitwarden-cli'
brew 'bottom'
brew 'boz/repo/kail'
brew 'coreutils'
brew 'curl'
brew 'eza'
brew 'fastfetch'
brew 'fd'
brew 'findutils'
brew 'fish'
brew 'fzf'
brew 'gabrie30/utils/ghorg'
brew 'git'
brew 'git-extras'
brew 'git-filter-repo'
brew 'glow'
brew 'gnu-sed'
brew 'gnupg'
brew 'gnutls'
brew 'go-task'
brew 'grep'
brew 'gron'
brew 'hashicorp/tap/terraform'
brew 'hashicorp/tap/vault'
brew 'helm'
brew 'jq'
brew 'jwt-cli'
brew 'k6'
brew 'k9s'
brew 'ktlint'
brew 'kubectl'
brew 'kubectx'
brew 'kustomize'
brew 'lazydocker'
brew 'lazygit'
brew 'lua'
brew 'luarocks'
brew 'magic-wormhole'
brew 'node'
brew 'npm'
brew 'nvim'
brew 'ollama'
brew 'openssl'
brew 'pipx'
brew 'poppler'
brew 'postgresql@16'
brew 'protobuf'
brew 'pyenv'
brew 'ripgrep'
brew 'ripgrep-all'
brew 'shellcheck'
brew 'slides'
brew 'starship'
brew 'stow'
brew 'stylua'
brew 'telnet'
brew 'tflint'
brew 'tldr'
brew 'trash'
brew 'tree'
brew 'uv'
brew 'watch'
brew 'wget'
brew 'wrk'
brew 'yarn'
brew 'yazi'
brew 'yq'
brew 'zoxide'
brew 'zsh'

# Casks
cask 'alacritty'
cask 'bluesnooze'
cask 'caffeine'
cask 'calibre'
cask 'firefox'
cask 'firefox@developer-edition'
cask 'font-fira-code'
cask 'font-fira-mono-nerd-font'
cask 'font-iosevka'
cask 'font-iosevka-nerd-font'
cask 'font-iosevka-term-nerd-font'
cask 'font-noto-mono'
cask 'font-noto-emoji'
cask 'ghostty@tip'
cask 'jetbrains-toolbox'
cask 'keymapp'
cask 'kitty'
cask 'microsoft-office'
cask 'microsoft-teams'
cask 'obsidian'
cask 'raycast'
cask 'slack'
cask 'spotify', args: { require_sha: false }
cask 'ticktick'
cask 'visual-studio-code'
cask 'vivaldi'

# Under test
cask 'appcleaner'
cask 'jdk-mission-control'
cask 'visualvm'
brew 'gum'
brew 'graphviz'

# Python: managed by pip, pipx and pyenv
# https://raw.githubusercontent.com/paeneumbra/dotfiles/blob/main/taskfiles/taskfile.python.yml

# Java: managed by sdkman
# https://raw.githubusercontent.com/paeneumbra/dotfiles/blob/main/taskfiles/taskfile.sdkman.yml

# Nvm: Manual installation
# https://github.com/nvm-sh/nvm?tab=readme-ov-file#installing-and-updating

# Docker: Manual installation
# https://docs.docker.com/desktop/setup/install/mac-install/

# Terraform
# terraform and tfenv conflict if both are installed
# brew 'tfenv'
# brew 'tfsec'

# Docker
# Sometimes just stops working for no apparent reason
# works when installed from docker.com
# cask 'docker'

# Unused
# brew 'httpie'
# cask 'postman'
# cask 'insomnia'
# cask 'wezterm'
# cask 'font-zed-mono-nerd-font'
