#!/usr/bin/env zsh

THEME_DIR="$CONFIG_DIR/theme"
ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

source "$THEME_DIR/colors.sh"
source "$THEME_DIR/icons.sh"
source "$THEME_DIR/styles.sh"

##### Bar Appearance #####
# https://felixkratz.github.io/SketchyBar/config/bar

bar=(
  blur_radius="$BLUR_LEVEL"
  border_color="$COLOR_BLUE"
  border_width="$BORDER_WIDTH"
  color="$COLOR_BACKGROUND_TRANSPARENT"
  corner_radius="$BORDER_RADIUS"
  height="$BAR_HEIGHT"
  margin="$BAR_MARGIN"
  padding_left="$BAR_PADDING"
  padding_right="$BAR_PADDING"
  position=top
  shadow=on
  sticky=on
  topmost=window
  y_offset="$BAR_OFFSET_TOP"
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  background.border_width="$BORDER_WIDTH"
  background.corner_radius="$BORDER_RADIUS"
  background.height="$ITEM_HEIGHT"
  icon.color="$COLOR_FOREGROUND"
  icon.font="$FONT_FACE:Bold:$FONT_SIZE_LARGE"
  icon.padding_left="$ICON_PADDING"
  icon.padding_right="$ICON_PADDING"
  label.color="$COLOR_FOREGROUND"
  label.font="$FONT_FACE:Medium:$FONT_SIZE"
  label.padding_left="$LABEL_PADDING"
  label.padding_right="$LABEL_PADDING"
  padding_left="$ITEM_PADDING"
  padding_right="$ITEM_PADDING"
  popup.background.border_color="$COLOR_ACCENT"
  popup.background.border_width="$BORDER_WIDTH"
  popup.background.color="$COLOR_BACKGROUND"
  popup.background.corner_radius="$BORDER_RADIUS"
  popup.background.shadow.drawing=on
  popup.blur_radius="$BLUR_LEVEL"
  scroll_texts=on
  updates=when_shown
)

sketchybar --default "${defaults[@]}"

# -- Left Side Items --
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/slack.sh"

# -- Right Side Items --
source "$ITEM_DIR/network.sh"
source "$ITEM_DIR/time.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/keyboard.sh"
source "$ITEM_DIR/volume.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
